const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Vimeo } = require('@vimeo/vimeo');

/**
 * Thin wrapper around the official Vimeo Node SDK: upload a rendered file, set its title/
 * description, and add it to a fixed set of showcases (Vimeo's API still calls these "albums" -
 * same feature, older name).
 *
 * Two ways to authenticate, both via environment variables (see .env.example) so no credentials
 * ever touch the codebase or get committed:
 *  - Legacy: a single VIMEO_ACCESS_TOKEN, generated by hand on developer.vimeo.com. Works
 *    immediately, no in-app connect step, but has to be copied into .env on every machine by hand.
 *  - OAuth: VIMEO_CLIENT_ID + VIMEO_CLIENT_SECRET identify the app (same values developer.vimeo.com
 *    shows when generating a token the old way) - with those in .env, a "Connect Vimeo" button
 *    in the app does the actual per-account authorization, and the resulting token is kept in
 *    data/vimeo-tokens.json (gitignored, same as SoundCloud's tokens file). Still needs the two
 *    client values in .env per machine, but the account-linking step itself becomes a button
 *    instead of hand-generating and pasting a token.
 * If VIMEO_ACCESS_TOKEN is set, it always wins - simplest to reason about, and keeps existing
 * installs working unchanged.
 */

const DATA_DIR = path.join(__dirname, '..', 'data');
const TOKENS_PATH = path.join(DATA_DIR, 'vimeo-tokens.json');

const SCOPES = ['public', 'private', 'upload', 'edit', 'interact'];

function hasLegacyToken() {
  return !!process.env.VIMEO_ACCESS_TOKEN;
}

function hasOAuthApp() {
  return !!(process.env.VIMEO_CLIENT_ID && process.env.VIMEO_CLIENT_SECRET);
}

function isConfigured() {
  return hasLegacyToken() || hasOAuthApp();
}

function getRedirectUri() {
  return process.env.VIMEO_REDIRECT_URI || 'http://localhost:3000/api/vimeo/oauth-callback';
}

function getShowcaseIds() {
  return (process.env.VIMEO_SHOWCASE_IDS || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

function loadTokens() {
  try {
    return JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf8'));
  } catch {
    return null;
  }
}

function saveTokens(tokens) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(TOKENS_PATH, JSON.stringify(tokens, null, 2));
}

// True as soon as there's a usable access token from either method - the legacy token needs no
// further setup, while the OAuth path only counts once "Connect Vimeo" has actually been done.
function isConnected() {
  if (hasLegacyToken()) return true;
  const tokens = loadTokens();
  return !!(tokens && tokens.access_token);
}

// Single-user local app - an in-memory set of valid `state` values is plenty to confirm the
// OAuth redirect that comes back seconds later is the one we sent, no real security boundary
// being crossed here, just CSRF-style plumbing (mirrors soundcloud.js's pendingAuth).
const pendingStates = new Set();

function getAuthorizeUrl() {
  if (!hasOAuthApp()) {
    throw new Error('Vimeo OAuth is not configured - set VIMEO_CLIENT_ID and VIMEO_CLIENT_SECRET in .env.');
  }
  const client = new Vimeo(process.env.VIMEO_CLIENT_ID, process.env.VIMEO_CLIENT_SECRET);
  const state = crypto.randomBytes(16).toString('hex');
  pendingStates.add(state);
  setTimeout(() => pendingStates.delete(state), 10 * 60 * 1000).unref();
  return client.buildAuthorizationEndpoint(getRedirectUri(), SCOPES, state);
}

async function handleOAuthCallback(code, state) {
  if (!pendingStates.has(state)) {
    throw new Error('This Vimeo sign-in link expired or was already used - click Connect Vimeo again.');
  }
  pendingStates.delete(state);

  const client = new Vimeo(process.env.VIMEO_CLIENT_ID, process.env.VIMEO_CLIENT_SECRET);
  const token = await new Promise((resolve, reject) => {
    client.accessToken(code, getRedirectUri(), (err, data) => {
      if (err) return reject(new Error(typeof err === 'string' ? err : err.message || 'Vimeo token exchange failed.'));
      resolve(data);
    });
  });
  if (!token || !token.access_token) throw new Error('Vimeo did not return an access token.');
  saveTokens({ access_token: token.access_token, user: token.user, obtained_at: Date.now() });
}

function getClient() {
  if (hasLegacyToken()) {
    return new Vimeo(process.env.VIMEO_CLIENT_ID || null, process.env.VIMEO_CLIENT_SECRET || null, process.env.VIMEO_ACCESS_TOKEN);
  }
  const tokens = loadTokens();
  if (tokens && tokens.access_token) {
    return new Vimeo(process.env.VIMEO_CLIENT_ID || null, process.env.VIMEO_CLIENT_SECRET || null, tokens.access_token);
  }
  throw new Error('Vimeo is not connected - set VIMEO_ACCESS_TOKEN in .env, or use Connect Vimeo.');
}

/**
 * Looks up the real name of each configured showcase, so the UI can offer a friendly checkbox
 * list instead of raw IDs. A showcase whose lookup fails (bad ID, no longer accessible) still
 * shows up - just labeled with the ID and flagged - rather than silently vanishing from the list.
 */
async function getShowcaseDetails() {
  const client = getClient();
  const showcaseIds = getShowcaseIds();
  // Independent lookups, run together rather than one-at-a-time - order is preserved either
  // way since Promise.all keeps results aligned with the input array regardless of timing.
  return Promise.all(
    showcaseIds.map(async (id) => {
      try {
        const res = await client.request({ method: 'GET', path: `/albums/${id}` });
        return { id, name: (res.body && res.body.name) || `Showcase ${id}` };
      } catch (err) {
        return { id, name: `Showcase ${id} (not found)`, error: err.message || String(err) };
      }
    })
  );
}

const VALID_PRIVACY_VIEWS = ['anybody', 'unlisted', 'nobody'];

/**
 * Uploads `filePath` to Vimeo with the given title/description/privacy, then adds it to
 * `showcaseIds` (defaults to every ID in VIMEO_SHOWCASE_IDS if not given - e.g. a caller that
 * never offered a choice). A failure adding to one showcase doesn't abort the others - the
 * result reports per-showcase success/failure so the caller can surface exactly what happened.
 */
async function uploadAndPublish({ filePath, name, description, showcaseIds, privacy, onProgress }) {
  const client = getClient();
  const privacyView = VALID_PRIVACY_VIEWS.includes(privacy) ? privacy : 'anybody';

  const videoUri = await new Promise((resolve, reject) => {
    client.upload(
      filePath,
      { name, description, privacy: { view: privacyView } },
      (uri) => resolve(uri),
      (bytesUploaded, bytesTotal) => {
        if (onProgress && bytesTotal > 0) onProgress(bytesUploaded / bytesTotal);
      },
      (err) => reject(new Error(typeof err === 'string' ? err : err.message || 'Vimeo upload failed.'))
    );
  });

  const videoId = videoUri.split('/').pop();
  const videoUrl = `https://vimeo.com/${videoId}`;

  const targetShowcaseIds = showcaseIds || getShowcaseIds();
  const showcaseResults = [];
  for (const showcaseId of targetShowcaseIds) {
    try {
      await client.request({ method: 'PUT', path: `/me/albums/${showcaseId}/videos/${videoId}` });
      showcaseResults.push({ showcaseId, ok: true });
    } catch (err) {
      showcaseResults.push({ showcaseId, ok: false, error: err.message || String(err) });
    }
  }

  return { videoUri, videoUrl, showcaseResults };
}

module.exports = { isConfigured, isConnected, getShowcaseIds, getShowcaseDetails, getAuthorizeUrl, handleOAuthCallback, uploadAndPublish };
