const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Vimeo } = require('@vimeo/vimeo');

/**
 * Thin wrapper around the official Vimeo Node SDK: upload a rendered file, set its title/
 * description, and add it to a fixed set of showcases (Vimeo's API still calls these "albums" -
 * same feature, older name).
 *
 * Two ways to authenticate:
 *  - Legacy: a single VIMEO_ACCESS_TOKEN in .env, generated by hand on developer.vimeo.com. Works
 *    immediately, no in-app setup, but has to be copied into .env on every machine by hand -
 *    a purely technical/advanced path, not something the app's own UI ever asks for.
 *  - OAuth (the normal path): a Client Identifier + Client Secret, entered right in the app via
 *    the Vimeo setup panel (see /api/vimeo-app-config below) rather than by editing any file -
 *    saved to data/vimeo-app-config.json (gitignored, never committed). With those saved, a
 *    "Connect Vimeo" button does the actual per-account authorization, and the resulting access
 *    token is kept in data/vimeo-tokens.json (gitignored, same pattern as SoundCloud's tokens
 *    file). VIMEO_CLIENT_ID/VIMEO_CLIENT_SECRET env vars still work too and take priority over
 *    the saved file, for anyone who'd rather manage it that way - but the file is the default.
 * If VIMEO_ACCESS_TOKEN is set, it always wins over both - simplest to reason about, and keeps
 * any existing legacy install working unchanged.
 */

const DATA_DIR = path.join(__dirname, '..', 'data');
const TOKENS_PATH = path.join(DATA_DIR, 'vimeo-tokens.json');
const APP_CONFIG_PATH = path.join(DATA_DIR, 'vimeo-app-config.json');
const ENV_PATH = path.join(__dirname, '..', '.env');

const SCOPES = ['public', 'private', 'upload', 'edit', 'interact'];

function hasLegacyToken() {
  return !!process.env.VIMEO_ACCESS_TOKEN;
}

function loadAppConfig() {
  try {
    return JSON.parse(fs.readFileSync(APP_CONFIG_PATH, 'utf8'));
  } catch {
    return null;
  }
}

function saveAppConfig({ clientId, clientSecret, showcaseIds }) {
  const existing = loadAppConfig() || {};
  const next = {
    clientId: clientId !== undefined ? String(clientId).trim() : existing.clientId || '',
    clientSecret: clientSecret !== undefined ? String(clientSecret).trim() : existing.clientSecret || '',
    showcaseIds: showcaseIds !== undefined ? showcaseIds : existing.showcaseIds || [],
  };
  if (!next.clientId || !next.clientSecret) {
    throw new Error('Both the Client Identifier and Client Secret are required.');
  }
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(APP_CONFIG_PATH, JSON.stringify(next, null, 2));
  return next;
}

// Clears the saved app credentials AND any connected account token - a full reset, for
// switching Vimeo accounts or starting over after a mistake.
function clearAppConfig() {
  fs.rmSync(APP_CONFIG_PATH, { force: true });
  fs.rmSync(TOKENS_PATH, { force: true });
}

// A bare VIMEO_ACCESS_TOKEN has no separate stored connection to clear - the env var the process
// was launched with *is* the connection, so the only way to actually sign out is to blank that
// line in .env and restart (env vars are only read once, at startup). Blanks the value rather
// than deleting the line, matching .env.example's style, and leaves everything else in the file
// untouched. Returns true if it actually changed something (there was a real value to clear).
function clearLegacyTokenFromEnvFile() {
  let content;
  try {
    content = fs.readFileSync(ENV_PATH, 'utf8');
  } catch {
    return false;
  }
  const updated = content.replace(/^VIMEO_ACCESS_TOKEN\s*=.*$/m, 'VIMEO_ACCESS_TOKEN=');
  if (updated === content) return false;
  fs.writeFileSync(ENV_PATH, updated);
  return true;
}

// Signs out of the connected Vimeo account without touching the saved (or env-provided) Client
// Identifier/Secret - lets Connect Vimeo be done again, e.g. to test the connect flow fresh or
// switch which Vimeo account is linked, without re-entering the app credentials. For the OAuth
// path this just clears the stored account token; for a legacy VIMEO_ACCESS_TOKEN, it also blanks
// that line in .env and reports that a restart is needed for the change to actually take effect.
function disconnect() {
  fs.rmSync(TOKENS_PATH, { force: true });
  const restartNeeded = hasLegacyToken() ? clearLegacyTokenFromEnvFile() : false;
  return { restartNeeded };
}

function getClientId() {
  return process.env.VIMEO_CLIENT_ID || (loadAppConfig() || {}).clientId || null;
}

function getClientSecret() {
  return process.env.VIMEO_CLIENT_SECRET || (loadAppConfig() || {}).clientSecret || null;
}

function hasOAuthApp() {
  return !!(getClientId() && getClientSecret());
}

function isConfigured() {
  return hasLegacyToken() || hasOAuthApp();
}

function getRedirectUri() {
  return process.env.VIMEO_REDIRECT_URI || 'http://localhost:3000/api/vimeo/oauth-callback';
}

function getShowcaseIds() {
  if (process.env.VIMEO_SHOWCASE_IDS) {
    return process.env.VIMEO_SHOWCASE_IDS.split(',').map((s) => s.trim()).filter(Boolean);
  }
  return (loadAppConfig() || {}).showcaseIds || [];
}

// Status for the client's setup panel - never includes the client secret itself, just whether
// one's been saved, so the UI can show "already saved" without round-tripping the actual value.
function getAppConfigStatus() {
  const config = loadAppConfig();
  return {
    clientId: process.env.VIMEO_CLIENT_ID || (config && config.clientId) || '',
    hasSecret: !!(process.env.VIMEO_CLIENT_SECRET || (config && config.clientSecret)),
    showcaseIds: getShowcaseIds(),
    // Env vars, if set, take priority and can't be edited from the app - the UI uses this to
    // explain why the fields are locked, rather than silently ignoring what's typed into them.
    lockedByEnv: !!(process.env.VIMEO_CLIENT_ID || process.env.VIMEO_CLIENT_SECRET),
  };
}

function loadTokens() {
  try {
    return JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf8'));
  } catch {
    return null;
  }
}

function saveTokens(tokens) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(TOKENS_PATH, JSON.stringify(tokens, null, 2));
}

// True as soon as there's a usable access token from either method - the legacy token needs no
// further setup, while the OAuth path only counts once "Connect Vimeo" has actually been done.
function isConnected() {
  if (hasLegacyToken()) return true;
  const tokens = loadTokens();
  return !!(tokens && tokens.access_token);
}

// Single-user local app - an in-memory set of valid `state` values is plenty to confirm the
// OAuth redirect that comes back seconds later is the one we sent, no real security boundary
// being crossed here, just CSRF-style plumbing (mirrors soundcloud.js's pendingAuth).
const pendingStates = new Set();

function getAuthorizeUrl() {
  if (!hasOAuthApp()) {
    throw new Error('Vimeo is not set up yet - fill in the Vimeo setup panel in the app first.');
  }
  const client = new Vimeo(getClientId(), getClientSecret());
  const state = crypto.randomBytes(16).toString('hex');
  pendingStates.add(state);
  setTimeout(() => pendingStates.delete(state), 10 * 60 * 1000).unref();
  return client.buildAuthorizationEndpoint(getRedirectUri(), SCOPES, state);
}

async function handleOAuthCallback(code, state) {
  if (!pendingStates.has(state)) {
    throw new Error('This Vimeo sign-in link expired or was already used - click Connect Vimeo again.');
  }
  pendingStates.delete(state);

  const client = new Vimeo(getClientId(), getClientSecret());
  const token = await new Promise((resolve, reject) => {
    client.accessToken(code, getRedirectUri(), (err, data) => {
      if (err) return reject(new Error(typeof err === 'string' ? err : err.message || 'Vimeo token exchange failed.'));
      resolve(data);
    });
  });
  if (!token || !token.access_token) throw new Error('Vimeo did not return an access token.');
  saveTokens({ access_token: token.access_token, user: token.user, obtained_at: Date.now() });
}

function getClient() {
  if (hasLegacyToken()) {
    return new Vimeo(getClientId(), getClientSecret(), process.env.VIMEO_ACCESS_TOKEN);
  }
  const tokens = loadTokens();
  if (tokens && tokens.access_token) {
    return new Vimeo(getClientId(), getClientSecret(), tokens.access_token);
  }
  throw new Error('Vimeo is not connected - use Connect Vimeo in the app first.');
}

/**
 * Looks up the real name of each configured showcase, so the UI can offer a friendly checkbox
 * list instead of raw IDs. A showcase whose lookup fails (bad ID, no longer accessible) still
 * shows up - just labeled with the ID and flagged - rather than silently vanishing from the list.
 */
async function getShowcaseDetails() {
  const client = getClient();
  const showcaseIds = getShowcaseIds();
  // Independent lookups, run together rather than one-at-a-time - order is preserved either
  // way since Promise.all keeps results aligned with the input array regardless of timing.
  return Promise.all(
    showcaseIds.map(async (id) => {
      try {
        const res = await client.request({ method: 'GET', path: `/albums/${id}` });
        return { id, name: (res.body && res.body.name) || `Showcase ${id}` };
      } catch (err) {
        return { id, name: `Showcase ${id} (not found)`, error: err.message || String(err) };
      }
    })
  );
}

const VALID_PRIVACY_VIEWS = ['anybody', 'unlisted', 'nobody'];

/**
 * Uploads `filePath` to Vimeo with the given title/description/privacy, then adds it to
 * `showcaseIds` (defaults to every ID in VIMEO_SHOWCASE_IDS if not given - e.g. a caller that
 * never offered a choice). A failure adding to one showcase doesn't abort the others - the
 * result reports per-showcase success/failure so the caller can surface exactly what happened.
 */
async function uploadAndPublish({ filePath, name, description, showcaseIds, privacy, onProgress }) {
  const client = getClient();
  const privacyView = VALID_PRIVACY_VIEWS.includes(privacy) ? privacy : 'anybody';

  const videoUri = await new Promise((resolve, reject) => {
    client.upload(
      filePath,
      { name, description, privacy: { view: privacyView } },
      (uri) => resolve(uri),
      (bytesUploaded, bytesTotal) => {
        if (onProgress && bytesTotal > 0) onProgress(bytesUploaded / bytesTotal);
      },
      (err) => reject(new Error(typeof err === 'string' ? err : err.message || 'Vimeo upload failed.'))
    );
  });

  const videoId = videoUri.split('/').pop();
  const videoUrl = `https://vimeo.com/${videoId}`;

  const targetShowcaseIds = showcaseIds || getShowcaseIds();
  const showcaseResults = [];
  for (const showcaseId of targetShowcaseIds) {
    try {
      await client.request({ method: 'PUT', path: `/me/albums/${showcaseId}/videos/${videoId}` });
      showcaseResults.push({ showcaseId, ok: true });
    } catch (err) {
      showcaseResults.push({ showcaseId, ok: false, error: err.message || String(err) });
    }
  }

  return { videoUri, videoUrl, showcaseResults };
}

module.exports = {
  isConfigured,
  isConnected,
  hasOAuthApp,
  getShowcaseIds,
  getShowcaseDetails,
  getAuthorizeUrl,
  handleOAuthCallback,
  getAppConfigStatus,
  saveAppConfig,
  clearAppConfig,
  disconnect,
  uploadAndPublish,
};
