const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Vimeo } = require('@vimeo/vimeo');

/**
 * Thin wrapper around the official Vimeo Node SDK: upload a rendered file, set its title/
 * description, and add it to a fixed set of showcases (Vimeo's API still calls these "albums" -
 * same feature, older name).
 *
 * Two ways to authenticate:
 *  - Legacy: a single VIMEO_ACCESS_TOKEN in .env, generated by hand on developer.vimeo.com. Works
 *    immediately, no in-app setup, but has to be copied into .env on every machine by hand -
 *    a purely technical/advanced path, not something the app's own UI ever asks for.
 *  - OAuth (the normal path): a Client Identifier + Client Secret, entered right in the app via
 *    the Vimeo setup panel (see /api/vimeo-app-config below) rather than by editing any file -
 *    saved to data/vimeo-app-config.json (gitignored, never committed). With those saved, a
 *    "Connect Vimeo" button does the actual per-account authorization, and the resulting access
 *    token is kept in data/vimeo-tokens.json (gitignored, same pattern as SoundCloud's tokens
 *    file). VIMEO_CLIENT_ID/VIMEO_CLIENT_SECRET env vars still work too and take priority over
 *    the saved file, for anyone who'd rather manage it that way - but the file is the default.
 * If VIMEO_ACCESS_TOKEN is set, it always wins over both - simplest to reason about, and keeps
 * any existing legacy install working unchanged.
 */

const DATA_DIR = path.join(__dirname, '..', 'data');
const TOKENS_PATH = path.join(DATA_DIR, 'vimeo-tokens.json');
const APP_CONFIG_PATH = path.join(DATA_DIR, 'vimeo-app-config.json');
const ENV_PATH = path.join(__dirname, '..', '.env');

const SCOPES = ['public', 'private', 'upload', 'edit', 'interact'];

function hasLegacyToken() {
  return !!process.env.VIMEO_ACCESS_TOKEN;
}

// Cached in memory after the first read - this app is the only writer of APP_CONFIG_PATH (both
// below), so there's no need to hit disk again on every getClientId()/getClientSecret()/etc.
// call. `undefined` means "not loaded yet"; `null` means "loaded, no file on disk".
let appConfigCache;

function loadAppConfig() {
  if (appConfigCache !== undefined) return appConfigCache;
  try {
    appConfigCache = JSON.parse(fs.readFileSync(APP_CONFIG_PATH, 'utf8'));
  } catch {
    appConfigCache = null;
  }
  return appConfigCache;
}

function saveAppConfig({ clientId, clientSecret, showcaseIds }) {
  const existing = loadAppConfig() || {};
  const next = {
    clientId: clientId !== undefined ? String(clientId).trim() : existing.clientId || '',
    clientSecret: clientSecret !== undefined ? String(clientSecret).trim() : existing.clientSecret || '',
  };
  // Leave the key out entirely rather than defaulting it to [], so "never set from the app" stays
  // distinguishable from "set to none" - that difference is what getShowcaseIds() uses to decide
  // whether VIMEO_SHOWCASE_IDS still applies. Writing [] here would silently empty the showcase
  // list of an install seeded from that variable, just for saving its credentials.
  if (showcaseIds !== undefined) next.showcaseIds = showcaseIds;
  else if (Array.isArray(existing.showcaseIds)) next.showcaseIds = existing.showcaseIds;
  if (!next.clientId || !next.clientSecret) {
    throw new Error('Both the Client Identifier and Client Secret are required.');
  }
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(APP_CONFIG_PATH, JSON.stringify(next, null, 2));
  appConfigCache = next;
  return next;
}

// Clears the saved app credentials AND any connected account token - a full reset, for
// switching Vimeo accounts or starting over after a mistake.
function clearAppConfig() {
  fs.rmSync(APP_CONFIG_PATH, { force: true });
  fs.rmSync(TOKENS_PATH, { force: true });
  appConfigCache = null;
}

// A bare VIMEO_ACCESS_TOKEN has no separate stored connection to clear - the env var the process
// was launched with *is* the connection, so the only way to actually sign out is to blank that
// line in .env and restart (env vars are only read once, at startup). Blanks the value rather
// than deleting the line, matching .env.example's style, and leaves everything else in the file
// untouched. Returns true if it actually changed something (there was a real value to clear).
function clearLegacyTokenFromEnvFile() {
  let content;
  try {
    content = fs.readFileSync(ENV_PATH, 'utf8');
  } catch {
    return false;
  }
  const updated = content.replace(/^VIMEO_ACCESS_TOKEN\s*=.*$/m, 'VIMEO_ACCESS_TOKEN=');
  if (updated === content) return false;
  fs.writeFileSync(ENV_PATH, updated);
  return true;
}

// Signs out of the connected Vimeo account without touching the saved (or env-provided) Client
// Identifier/Secret - lets Connect Vimeo be done again, e.g. to test the connect flow fresh or
// switch which Vimeo account is linked, without re-entering the app credentials. For the OAuth
// path this just clears the stored account token; for a legacy VIMEO_ACCESS_TOKEN, it also blanks
// that line in .env and reports that a restart is needed for the change to actually take effect.
function disconnect() {
  fs.rmSync(TOKENS_PATH, { force: true });
  const restartNeeded = hasLegacyToken() ? clearLegacyTokenFromEnvFile() : false;
  return { restartNeeded };
}

function getClientId() {
  return process.env.VIMEO_CLIENT_ID || (loadAppConfig() || {}).clientId || null;
}

function getClientSecret() {
  return process.env.VIMEO_CLIENT_SECRET || (loadAppConfig() || {}).clientSecret || null;
}

function hasOAuthApp() {
  return !!(getClientId() && getClientSecret());
}

function getRedirectUri() {
  return process.env.VIMEO_REDIRECT_URI || 'http://localhost:3000/api/vimeo/oauth-callback';
}

// The list saved from inside the app wins. VIMEO_SHOWCASE_IDS is only a starting point, for an
// install that was set up from a script and has never touched the app's own showcase controls -
// it used to override the saved list outright, which made adding or removing a showcase in the
// app look like it did nothing at all. Managing showcases is a routine job for whoever publishes
// sermons, so the app has to own it once it has been used.
function getShowcaseIds() {
  const config = loadAppConfig();
  if (config && Array.isArray(config.showcaseIds)) return config.showcaseIds;
  if (process.env.VIMEO_SHOWCASE_IDS) {
    return process.env.VIMEO_SHOWCASE_IDS.split(',').map((s) => s.trim()).filter(Boolean);
  }
  return [];
}

// Writes just the showcase list. Deliberately separate from saveAppConfig(), which insists on a
// Client Identifier and Secret - showcases can be lined up before the account is connected, and
// a half-finished setup shouldn't block editing them.
function saveShowcaseIds(showcaseIds) {
  const next = { ...(loadAppConfig() || {}), showcaseIds };
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(APP_CONFIG_PATH, JSON.stringify(next, null, 2));
  appConfigCache = next;
  return next.showcaseIds;
}

// Pulls the numeric ID out of whatever someone pastes: a showcase link in any of the shapes Vimeo
// hands out, or the bare number. Once connected the ID is checked against the account so a typo
// is caught here rather than silently failing at publish time.
async function resolveShowcase(input) {
  const trimmed = String(input || '').trim();
  if (!trimmed) throw new Error('Paste a showcase link or ID first.');
  const fromUrl = trimmed.match(/(?:showcases?|albums?)\/(\d+)/i);
  const id = fromUrl ? fromUrl[1] : (/^\d+$/.test(trimmed) ? trimmed : null);
  if (!id) {
    throw new Error('That doesn\'t look like a showcase link or ID - a showcase link ends in a number, e.g. vimeo.com/showcase/1234567.');
  }
  if (!isConnected()) return { id, name: `Showcase ${id}` };
  try {
    const res = await getClient().request({ method: 'GET', path: `/albums/${id}` });
    return { id, name: (res.body && res.body.name) || `Showcase ${id}` };
  } catch {
    throw new Error(`No showcase ${id} on the connected Vimeo account - check the link and try again.`);
  }
}

// Status for the client's setup panel - never includes the client secret itself, just whether
// one's been saved, so the UI can show "already saved" without round-tripping the actual value.
function getAppConfigStatus() {
  const config = loadAppConfig();
  return {
    clientId: process.env.VIMEO_CLIENT_ID || (config && config.clientId) || '',
    hasSecret: !!(process.env.VIMEO_CLIENT_SECRET || (config && config.clientSecret)),
    showcaseIds: getShowcaseIds(),
    // Env vars, if set, take priority and can't be edited from the app - the UI uses this to
    // explain why the fields are locked, rather than silently ignoring what's typed into them.
    lockedByEnv: !!(process.env.VIMEO_CLIENT_ID || process.env.VIMEO_CLIENT_SECRET),
    // True only while the list is still coming from VIMEO_SHOWCASE_IDS because nothing has been
    // saved from the app yet. Purely informational now - the app's own list takes over the first
    // time a showcase is added or removed, so this never blocks an edit.
    showcaseIdsFromEnv: !(config && Array.isArray(config.showcaseIds)) && !!process.env.VIMEO_SHOWCASE_IDS,
  };
}

function loadTokens() {
  try {
    return JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf8'));
  } catch {
    return null;
  }
}

function saveTokens(tokens) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(TOKENS_PATH, JSON.stringify(tokens, null, 2));
}

// True as soon as there's a usable access token from either method - the legacy token needs no
// further setup, while the OAuth path only counts once "Connect Vimeo" has actually been done.
function isConnected() {
  if (hasLegacyToken()) return true;
  const tokens = loadTokens();
  return !!(tokens && tokens.access_token);
}

// Single-user local app - an in-memory set of valid `state` values is plenty to confirm the
// OAuth redirect that comes back seconds later is the one we sent, no real security boundary
// being crossed here, just CSRF-style plumbing (mirrors soundcloud.js's pendingAuth).
const pendingStates = new Set();

function getAuthorizeUrl() {
  if (!hasOAuthApp()) {
    throw new Error('Vimeo is not set up yet - fill in the Vimeo setup panel in the app first.');
  }
  const client = new Vimeo(getClientId(), getClientSecret());
  const state = crypto.randomBytes(16).toString('hex');
  pendingStates.add(state);
  setTimeout(() => pendingStates.delete(state), 10 * 60 * 1000).unref();
  return client.buildAuthorizationEndpoint(getRedirectUri(), SCOPES, state);
}

async function handleOAuthCallback(code, state) {
  if (!pendingStates.has(state)) {
    throw new Error('This Vimeo sign-in link expired or was already used - click Connect Vimeo again.');
  }
  pendingStates.delete(state);

  const client = new Vimeo(getClientId(), getClientSecret());
  const token = await new Promise((resolve, reject) => {
    client.accessToken(code, getRedirectUri(), (err, data) => {
      if (err) return reject(new Error(typeof err === 'string' ? err : err.message || 'Vimeo token exchange failed.'));
      resolve(data);
    });
  });
  if (!token || !token.access_token) throw new Error('Vimeo did not return an access token.');
  saveTokens({ access_token: token.access_token, user: token.user, obtained_at: Date.now() });
}

function getClient() {
  if (hasLegacyToken()) {
    return new Vimeo(getClientId(), getClientSecret(), process.env.VIMEO_ACCESS_TOKEN);
  }
  const tokens = loadTokens();
  if (tokens && tokens.access_token) {
    return new Vimeo(getClientId(), getClientSecret(), tokens.access_token);
  }
  throw new Error('Vimeo is not connected - use Connect Vimeo in the app first.');
}

/**
 * Looks up the real name of each configured showcase, so the UI can offer a friendly checkbox
 * list instead of raw IDs. A showcase whose lookup fails (bad ID, no longer accessible) still
 * shows up - just labeled with the ID and flagged - rather than silently vanishing from the list.
 */
async function getShowcaseDetails() {
  const client = getClient();
  const showcaseIds = getShowcaseIds();
  // Independent lookups, run together rather than one-at-a-time - order is preserved either
  // way since Promise.all keeps results aligned with the input array regardless of timing.
  return Promise.all(
    showcaseIds.map(async (id) => {
      try {
        const res = await client.request({ method: 'GET', path: `/albums/${id}` });
        return { id, name: (res.body && res.body.name) || `Showcase ${id}` };
      } catch (err) {
        return { id, name: `Showcase ${id} (not found)`, error: err.message || String(err) };
      }
    })
  );
}

const VALID_PRIVACY_VIEWS = ['anybody', 'unlisted', 'nobody'];

function guessImageContentType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === '.jpg' || ext === '.jpeg') return 'image/jpeg';
  if (ext === '.gif') return 'image/gif';
  if (ext === '.webp') return 'image/webp';
  return 'image/png';
}

/**
 * Uploads `imagePath` as a custom thumbnail for the video at `videoUri` and makes it the active
 * one - Vimeo's Pictures API: create a picture resource (which hands back a one-time upload
 * link), PUT the raw image bytes there, then PATCH that picture to `active: true`. The upload
 * link points at Vimeo's storage host, not api.vimeo.com, so it's a plain fetch() rather than
 * client.request() (which always targets the API host).
 */
async function setThumbnail(videoUri, imagePath) {
  const client = getClient();
  const created = await client.request({ method: 'POST', path: `${videoUri}/pictures` });
  const body = created.body || {};
  // The Pictures API hands back the pre-signed target to PUT the image bytes to as `link` on the
  // picture itself. This used to look for `upload.upload_link`, which is the shape Vimeo uses for
  // *video* uploads - so it was never present here and every custom thumbnail failed with
  // "Vimeo did not return an upload link". The older field is still accepted in case an account
  // is served the other shape.
  const uploadLink = body.link || (body.upload && body.upload.upload_link);
  const pictureUri = body.uri;
  if (!uploadLink || !pictureUri) {
    // Naming what did come back turns a repeat of this into a five-second diagnosis instead of
    // a guess about which field moved.
    throw new Error(`Vimeo did not return an upload link for the thumbnail (it replied with: ${Object.keys(body).join(', ') || 'nothing'}).`);
  }

  const imageBuffer = await fs.promises.readFile(imagePath);
  const putRes = await fetch(uploadLink, {
    method: 'PUT',
    headers: { 'Content-Type': guessImageContentType(imagePath) },
    body: imageBuffer,
  });
  if (!putRes.ok) {
    throw new Error(`Uploading the thumbnail image to Vimeo failed (${putRes.status}).`);
  }

  await client.request({ method: 'PATCH', path: pictureUri, query: { active: true } });

  // Ask Vimeo what the video's thumbnail actually is now, rather than assuming the PATCH stuck.
  // A video's `pictures.type` reads "custom" when an uploaded image is the active one and
  // "default" when Vimeo is still showing a frame it picked itself - which is exactly the
  // difference between the graphic someone chose and the "wrong picture" they end up reporting.
  // Retried briefly because the video is usually still transcoding at this point and the change
  // does not always read back instantly.
  for (let attempt = 0; attempt < 3; attempt += 1) {
    if (attempt > 0) await new Promise((resolve) => setTimeout(resolve, 2000));
    try {
      const check = await client.request({ method: 'GET', path: `${videoUri}?fields=pictures.type` });
      const type = check.body && check.body.pictures && check.body.pictures.type;
      if (type === 'custom') {
        const removed = await removeOtherPictures(client, videoUri, pictureUri);
        return { confirmed: true, removedPictures: removed };
      }
    } catch {
      // Keep trying - a failed read says nothing about whether the thumbnail took.
    }
  }
  // Not an error: the image uploaded fine and Vimeo accepted it. It just is not showing yet, and
  // saying so is far more useful than silence when someone is asking why the picture is wrong.
  return { confirmed: false, removedPictures: 0 };
}

/**
 * Deletes every picture on the video except `keepUri`, leaving exactly one thumbnail.
 *
 * Vimeo keeps every picture ever attached to a video and offers all of them in its thumbnail
 * picker, so each publish left the uploaded graphic sitting next to the frame Vimeo generated
 * for itself - two near-identical choices, since these videos open on that very graphic. Only
 * one is ever wanted.
 *
 * Deliberately only called once the uploaded picture is confirmed active, so there is no way to
 * strip a video back to nothing: the one being kept is known to be the one on display. Failures
 * are swallowed - an extra thumbnail left behind is untidy, not broken, and never worth failing
 * a publish over.
 */
async function removeOtherPictures(client, videoUri, keepUri) {
  let removed = 0;
  try {
    const listed = await client.request({ method: 'GET', path: `${videoUri}/pictures?fields=uri&per_page=100` });
    const pictures = (listed.body && listed.body.data) || [];
    for (const picture of pictures) {
      if (!picture.uri || picture.uri === keepUri) continue;
      try {
        await client.request({ method: 'DELETE', path: picture.uri });
        removed += 1;
      } catch {
        // Some pictures can't be deleted; leaving one behind is harmless.
      }
    }
  } catch {
    // Couldn't list them - nothing to tidy, and nothing worth reporting.
  }
  return removed;
}

/**
 * Uploads `filePath` to Vimeo with the given title/description/privacy, then adds it to
 * `showcaseIds` (defaults to every ID in VIMEO_SHOWCASE_IDS if not given - e.g. a caller that
 * never offered a choice). A failure adding to one showcase doesn't abort the others - the
 * result reports per-showcase success/failure so the caller can surface exactly what happened.
 * `thumbnailPath`, if given, is set as the video's custom thumbnail - best-effort, since a
 * thumbnail failure shouldn't undo an otherwise-successful video upload.
 */
async function uploadAndPublish({ filePath, name, description, showcaseIds, privacy, thumbnailPath, onProgress }) {
  const client = getClient();
  const privacyView = VALID_PRIVACY_VIEWS.includes(privacy) ? privacy : 'anybody';

  const videoUri = await new Promise((resolve, reject) => {
    client.upload(
      filePath,
      { name, description, privacy: { view: privacyView } },
      (uri) => resolve(uri),
      (bytesUploaded, bytesTotal) => {
        if (onProgress && bytesTotal > 0) onProgress(bytesUploaded / bytesTotal);
      },
      (err) => reject(new Error(typeof err === 'string' ? err : err.message || 'Vimeo upload failed.'))
    );
  });

  const videoId = videoUri.split('/').pop();
  const videoUrl = `https://vimeo.com/${videoId}`;

  let thumbnailError = null;
  let thumbnailConfirmed = false;
  if (thumbnailPath) {
    try {
      ({ confirmed: thumbnailConfirmed } = await setThumbnail(videoUri, thumbnailPath));
    } catch (err) {
      thumbnailError = err.message || String(err);
    }
  }

  const targetShowcaseIds = showcaseIds || getShowcaseIds();
  const showcaseResults = [];
  for (const showcaseId of targetShowcaseIds) {
    try {
      await client.request({ method: 'PUT', path: `/me/albums/${showcaseId}/videos/${videoId}` });
      showcaseResults.push({ showcaseId, ok: true });
    } catch (err) {
      showcaseResults.push({ showcaseId, ok: false, error: err.message || String(err) });
    }
  }

  return { videoUri, videoUrl, showcaseResults, thumbnailError, thumbnailSet: !!thumbnailPath, thumbnailConfirmed };
}

module.exports = {
  // Exported for tests only - the real caller reaches it through uploadAndPublish().
  __test_setThumbnail: setThumbnail,
  isConnected,
  hasOAuthApp,
  getShowcaseIds,
  getShowcaseDetails,
  saveShowcaseIds,
  resolveShowcase,
  getAuthorizeUrl,
  handleOAuthCallback,
  getAppConfigStatus,
  saveAppConfig,
  clearAppConfig,
  disconnect,
  uploadAndPublish,
};
